import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PermanentDrawerRight from "./drawer";

const mode = "dark"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {



  return (
    <html lang="en" dir="rtl">
      <div>ssssssssssssssssss</div>
      <body className={inter.className}>
        <PermanentDrawerRight/>
        {children}
      </body>
    </html>
  );
}
