import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Disclosure, DisclosureButton } from "@headlessui/react";
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline'
import Link from "next/link";
import { log } from "console";
import Header from "./(commponads)/Header";
import Footer from "./(commponads)/Footer";
import PermanentDrawerRight from "./(commponads)/draw";


const mode = "dark"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {



  return (
    <html lang="en" dir="rtl">

      <body className={inter.className}>
          <Header />
          <PermanentDrawerRight />
          {children}

      </body>
    </html>
  );
}
